LANGUAGES = {
'ab': 'abkhazian',
'ace': 'acehnese',
'ach': 'acoli',
'aa': 'afar',
'af': 'afrikaans',
'ay': 'aymara',
'ga': 'irish',
'sq': 'albanian',
'alur': 'alur',
'am': 'amharic',
'en': 'english',
'ar': 'arabic',
'hy': 'armenian',
'as': 'assamese',
'awa': 'awadhi',
'av': 'avaric',
'az': 'azerbaijani',
'ban': 'balinese',
'be': 'belarusian',
'bal': 'baluchi',
'bm': 'bambara',
'eu': 'basque',
'ba': 'bashkir',
'bbc': 'batak karo',
'bts': 'batak simalungun',
'btx': 'batak toba',
'bci': 'baule',
'bem': 'bemba',
'bn': 'bengali',
'bew': 'betawi',
'bho': 'bhojpuri',
'bik': 'bikol',
'my': 'burmese',
'bs': 'bosnian',
'bua': 'buriat',
'br': 'breton',
'bg': 'bulgarian',
'bua': 'buriat',
'ch': 'chamorro',
'ce': 'chechen',
'cs': 'czech',
'ny': 'chichewa',
'cgg': 'chiga',
'cv': 'chuvash',
'ceb': 'cebuano',
'da': 'danish',
'prs': 'dari',
'din': 'dinka',
'dyu': 'dyula',
'dv': 'divehi',
'doi': 'dogri',
'dov': 'dombe',
'kac': 'jingpho',
'ik': 'inupiaq',
'ikt': 'inuktitut syllabics',
'eo': 'esperanto',
'et': 'estonian',
'ee': 'ewe',
'fo': 'faroese',
'fj': 'fijian',
'fon': 'fon',
'fur': 'friulian',
'fy': 'frisian',
'ff': 'fulani',
'gaa': 'ga',
'gl': 'galician',
'el': 'greek',
'kl': 'greenlandic',
'ka': 'georgian',
'gu': 'gujarati',
'gn': 'guarani',
'ht': 'haitian creole',
'cnh': 'hakha chin',
'ha': 'hausa',
'haw': 'hawaiian',
'he': 'hebrew',
'hi': 'hindi',
'hmn': 'hmong',
'hrx': 'hunsrik',
'iba': 'iban',
'ig': 'igbo',
'ilo': 'ilocano',
'ilk': 'ilonggo',
'id': 'indonesian',
'is': 'icelandic',
'es': 'spanish',
'it': 'italian',
'sah': 'yakut',
'jam': 'jamaican creole',
'ja': 'japanese',
'jv': 'javanese',
'yi': 'yiddish',
'yo': 'yoruba',
'yua': 'yucatec maya',
'kn': 'kannada',
'yue': 'cantonese',
'knc': 'kanuri',
'pam': 'kapampangan',
'ca': 'catalan',
'kk': 'kazakh',
'qu': 'quechua',
'kek': 'kekchi',
'kha': 'khasi',
'km': 'khmer',
'kg': 'kikongo',
'rw': 'kinyarwanda',
'zh-CN': 'chinese (simplified)',
'zh-TW': 'chinese (traditional)',
'ky': 'kyrgyz',
'ktu': 'kituba',
'trp': 'kokborok',
'kv': 'komi',
'kok': 'konkani',
'ko': 'korean',
'co': 'corsican',
'xh': 'xhosa',
'crh-Cyrl': 'crimean tatar (cyrillic)',
'crh': 'crimean tatar (latin)',
'kri': 'krio',
'hr': 'croatian',
'ku': 'kurdish (kurmanji)',
'ckb': 'kurdish (sorani)',
'lo': 'lao',
'ltg': 'latgalian',
'lv': 'latvian',
'pl': 'polish',
'lt': 'lithuanian',
'mhr': 'meadow mari',
'lij': 'ligurian',
'li': 'limburgish',
'ln': 'lingala',
'lb': 'luxembourgish',
'lmo': 'lombard',
'la': 'latin',
'lg': 'luganda',
'luo': 'luo',
'mad': 'madurese',
'mai': 'maithili',
'mak': 'makassarese',
'mk': 'macedonian',
'mg': 'malagasy',
'ml': 'malayalam',
'ms': 'malay',
'ms-Arab': 'malay (jawi)',
'mt': 'maltese',
'mam': 'mam',
'mni': 'manipuri',
'mi': 'maori',
'mr': 'marathi',
'mh': 'marshallese',
'mwr': 'marwari',
'mfe': 'mauritian creole',
'min': 'minangkabau',
'lus': 'mizo',
'mn': 'mongolian',
'nhe': 'nahuatl (eastern huasteca)',
'ndc': 'ndau',
'nr': 'ndebele (south)',
'ne': 'nepali',
'new': 'newari',
'nqo': 'nko',
'no': 'norwegian',
'nus': 'nuer',
'oc': 'occitan',
'nl': 'dutch',
'or': 'odia',
'om': 'oromo',
'os': 'ossetian',
'pag': 'pangasinan',
'pap': 'papiamento',
'tpi': 'tok pisin',
'pa-Arab': 'punjabi (shahmukhi)',
'pa': 'punjabi (gurmukhi)',
'fa': 'persian',
'pt-BR': 'portuguese (brazil)',
'pt-PT': 'portuguese (portugal)',
'fr': 'french',
'fr-CA': 'french (canada)',
'ps': 'pashto',
'rom': 'romani',
'ro': 'romanian',
'rn': 'rundi',
'ru': 'russian',
'se': 'northern sami',
'sm': 'samoan',
'sg': 'sango',
'sa': 'sanskrit',
'sat-Latn': 'santali (latin)',
'sat': 'santali (ol chiki)',
'ceb': 'cebuano',
'crs': 'seychellois creole',
'nso': 'sepedi',
'sr': 'serbian',
'st': 'sesotho',
'scn': 'sicilian',
'szl': 'silesian',
'sd': 'sindhi',
'si': 'sinhala',
'sk': 'slovak',
'sl': 'slovenian',
'so': 'somali',
'su': 'sundanese',
'fi': 'finnish',
'sus': 'susu',
'sw': 'swahili',
'ss': 'swati',
'shn': 'shan',
'sco': 'scots',
'sn': 'shona',
'sv': 'swedish',
'tg': 'tajik',
'tl': 'tagalog',
'ty': 'tahitian',
'th': 'thai',
'tzm-Tfng': 'tamazight (tifinagh)',
'ber': 'tamazight',
'ta': 'tamil',
'te': 'telugu',
'tet': 'tetum',
'bo': 'tibetan',
'ti': 'tigrinya',
'tiv': 'tiv',
'to': 'tongan',
'tt': 'tatar',
'tshiluba': 'tshiluba',
'ts': 'tsonga',
'tn': 'tswana',
'tcy': 'tulu',
'tum': 'tumbuka',
'tk': 'turkmen',
'tr': 'turkish',
'tyv': 'tuvan',
'tw': 'twi',
'udm': 'udmurt',
'ug': 'uyghur',
'uk': 'ukrainian',
'ur': 'urdu',
'uz': 'uzbek',
'cy': 'welsh',
'war': 'waray',
've': 'venda',
'vec': 'venetian',
'hu': 'hungarian',
'vi': 'vietnamese',
'de': 'german',
'wo': 'wolof',
'zap': 'zapotec',
'zu': 'zulu',}

keys = [key for key in LANGUAGES.keys()]
values = [key for key in LANGUAGES.values()]